apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workshop-exercise05
  namespace: openshift-gitops
  labels:
    type: workshop-trbl
spec:
  destination:
    name: in-cluster
    namespace: default
  project: trbl-workshop
  source:
    path: trbl-workshop/setup/exercise-05
    repoURL: https://github.com/grantomation/troubleshoot-workshop/
    targetRevision: main
    helm:
      parameters:
      - name: "userCount"
        value: "20"


