apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workshop-exercise06
  namespace: openshift-gitops
  labels:
    type: workshop-trbl
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    path: trbl-workshop/setup/exercise-06
    repoURL: https://github.com/grantomation/aro-troubleshoot-workshop/
    targetRevision: main
    helm:
      parameters:
      - name: "userCount"
        value: "1"
